default: styles/mastodon-bird-ui-dark.scss
mastodon-bird-ui-light: styles/mastodon-bird-ui-light.scss
mastodon-dark: styles/application.scss
mastodon-light: styles/mastodon-light.scss
contrast: styles/contrast.scss
mastodon-bird-ui-light-vanilla: styles/mastodon-bird-ui-light-vanilla.scss
mastodon-bird-ui-dark-vanilla: styles/mastodon-bird-ui-dark-vanilla.scss