# default: styles/mastodon-bird-ui-dark.scss
default: styles/hunter2-ui-lighthunter.scss
hunter2-ui-darkhunter: styles/hunter2-ui-darkhunter.scss
bird-ui-light: styles/bird-ui-light.scss
bird-ui-dark: styles/bird-ui-dark.scss
mastodon-light: styles/mastodon-light.scss
mastodon-dark: styles/application.scss
contrast: styles/contrast.scss